sudo: required
services:
  - docker


before_install:
  - docker build -t $DOCKER_ID/multiple-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run $DOCKER_ID/multiple-docker npm run test -- --env=jsdom --watchAll=false --coverage

after_success:
  #Log In Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Build Images
  - docker build -t multiple-client ./client
  - docker build -t multiple-nginx ./nginx
  - docker build -t multiple-server ./server
  - docker build -t multiple-worker ./worker
  
  #Tag Images
  - docker tag multiple-client $DOCKER_ID/multiple-client
  - docker tag multiple-nginx $DOCKER_ID/multiple-nginx
  - docker tag multiple-server $DOCKER_ID/multiple-server
  - docker tag multiple-worker $DOCKER_ID/multiple-worker

  #Take These Images into DOcker HUB
  - docker push $DOCKER_ID/multiple-client
  - docker push $DOCKER_ID/multiple-nginx
  - docker push $DOCKER_ID/multiple-server
  - docker push $DOCKER_ID/multiple-worker